import { CONFIG } from '../core/Config';
import { Music, type MusicMode } from './Music';

/**
 * Procedural audio built with the Web Audio API (no external sound assets).
 *
 * Bus graph: sfx / music -> master -> destination. Wind and snow-slide are
 * looping filtered-noise beds driven by speed; jump, landing, crash, checkpoint
 * and combo are short synthesised one-shots. Background music is generated by
 * Music. The context starts suspended until the first user gesture unlocks it.
 */
export class AudioSystem {
  private context: AudioContext | null = null;
  private master: GainNode | null = null;
  private sfxBus: GainNode | null = null;
  private musicBus: GainNode | null = null;
  private music: Music | null = null;
  private windGain: GainNode | null = null;
  private windFilter: BiquadFilterNode | null = null;
  private slideGain: GainNode | null = null;
  private slideFilter: BiquadFilterNode | null = null;
  private carveGain: GainNode | null = null;
  private carveFilter: BiquadFilterNode | null = null;
  private noiseBuffer: AudioBuffer | null = null;
  private enabled = true;

  private masterVolume = CONFIG.audio.masterVolume;
  private musicVolume = CONFIG.audio.musicVolume;
  private sfxVolume = CONFIG.audio.sfxVolume;
  private muted = false;
  private musicMode: MusicMode = 'none';

  constructor() {
    const unlock = () => this.unlock();
    window.addEventListener('pointerdown', unlock);
    window.addEventListener('keydown', unlock);
  }

  /** Creates / resumes the audio context. Safe to call repeatedly. */
  unlock(): void {
    if (!this.context) {
      const Ctor =
        window.AudioContext ??
        (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
      if (!Ctor) return;
      this.context = new Ctor();
      this.build();
    }
    if (this.context.state === 'suspended') void this.context.resume();
  }

  setEnabled(enabled: boolean): void {
    this.enabled = enabled;
    this.applyVolumes();
  }

  setMasterVolume(volume: number): void {
    this.masterVolume = Math.min(Math.max(volume, 0), 1);
    this.applyVolumes();
  }

  setMusicVolume(volume: number): void {
    this.musicVolume = Math.min(Math.max(volume, 0), 1);
    this.applyVolumes();
  }

  setSfxVolume(volume: number): void {
    this.sfxVolume = Math.min(Math.max(volume, 0), 1);
    this.applyVolumes();
  }

  setMuted(muted: boolean): void {
    this.muted = muted;
    this.applyVolumes();
  }

  setMusicMode(mode: MusicMode): void {
    this.musicMode = mode;
    this.music?.setMode(mode);
  }

  update(speed: number, grounded: boolean, lean = 0): void {
    if (!this.context || !this.windGain || !this.slideGain || !this.windFilter || !this.slideFilter)
      return;
    const a = CONFIG.audio;
    const t = Math.min(Math.max((speed - a.minSpeed) / (a.maxSpeed - a.minSpeed), 0), 1);
    const now = this.context.currentTime;
    this.windGain.gain.setTargetAtTime(t * a.windMaxGain, now, 0.12);
    this.windFilter.frequency.setTargetAtTime(420 + t * 900, now, 0.12);
    this.slideGain.gain.setTargetAtTime(grounded ? t * a.slideMaxGain : 0, now, 0.08);
    this.slideFilter.frequency.setTargetAtTime(1200 + t * 1400, now, 0.1);

    // Carve layer: louder the harder the board is edging, but only while riding.
    if (this.carveGain && this.carveFilter) {
      const carve = grounded ? Math.min(Math.abs(lean) / 0.35, 1) * t : 0;
      this.carveGain.gain.setTargetAtTime(carve * a.carveMaxGain, now, 0.08);
      this.carveFilter.frequency.setTargetAtTime(1800 + carve * 2200, now, 0.1);
    }
  }

  playJump(): void {
    this.tone('triangle', 320, 760, 0.24, 0.22);
  }

  playLanding(strength: number): void {
    this.noiseBurst(0.18 + strength * 0.2, 0.22 + strength * 0.25, 900 + strength * 700);
  }

  playCrash(): void {
    this.noiseBurst(0.5, 0.4, 500);
    this.tone('sawtooth', 180, 60, 0.4, 0.25);
  }

  playCheckpoint(): void {
    this.tone('sine', 660, 660, 0.12, 0.2);
    this.tone('sine', 990, 990, 0.16, 0.2, 0.1);
  }

  playCombo(level: number): void {
    const base = 440 * Math.pow(1.12, Math.max(0, level - 1));
    this.tone('sine', base, base * 1.5, 0.18, 0.18);
  }

  playCountdown(): void {
    this.tone('sine', 520, 520, 0.12, 0.2);
  }

  playGo(): void {
    this.tone('sine', 780, 780, 0.2, 0.24);
    this.tone('sine', 1040, 1040, 0.26, 0.2, 0.07);
  }

  playUiClick(): void {
    this.tone('triangle', 660, 660, 0.06, 0.12);
  }

  playUiBack(): void {
    this.tone('triangle', 420, 360, 0.08, 0.1);
  }

  playUiHover(): void {
    this.tone('sine', 880, 880, 0.04, 0.05);
  }

  private applyVolumes(): void {
    if (!this.context || !this.master || !this.musicBus || !this.sfxBus) return;
    const now = this.context.currentTime;
    const master = this.enabled && !this.muted ? this.masterVolume : 0;
    this.master.gain.setTargetAtTime(master, now, 0.05);
    this.musicBus.gain.setTargetAtTime(this.musicVolume, now, 0.05);
    this.sfxBus.gain.setTargetAtTime(this.sfxVolume, now, 0.05);
  }

  private build(): void {
    const ctx = this.context;
    if (!ctx) return;

    this.master = ctx.createGain();
    this.master.connect(ctx.destination);

    this.musicBus = ctx.createGain();
    this.musicBus.connect(this.master);
    this.sfxBus = ctx.createGain();
    this.sfxBus.connect(this.master);

    this.applyVolumes();

    this.noiseBuffer = this.createNoiseBuffer(ctx);

    this.music = new Music(ctx, this.musicBus);
    this.music.setMode(this.musicMode);
    this.music.start();

    // Wind: low-passed noise.
    this.windSourceSetup(ctx);

    // Snow slide: band-passed noise.
    const slideSource = ctx.createBufferSource();
    slideSource.buffer = this.noiseBuffer;
    slideSource.loop = true;
    this.slideFilter = ctx.createBiquadFilter();
    this.slideFilter.type = 'bandpass';
    this.slideFilter.frequency.value = 1400;
    this.slideFilter.Q.value = 0.7;
    this.slideGain = ctx.createGain();
    this.slideGain.gain.value = 0;
    slideSource.connect(this.slideFilter).connect(this.slideGain).connect(this.sfxBus);
    slideSource.start();

    // Carve: a brighter band of the same noise, driven by edge angle.
    const carveSource = ctx.createBufferSource();
    carveSource.buffer = this.noiseBuffer;
    carveSource.loop = true;
    this.carveFilter = ctx.createBiquadFilter();
    this.carveFilter.type = 'bandpass';
    this.carveFilter.frequency.value = 2200;
    this.carveFilter.Q.value = 1.2;
    this.carveGain = ctx.createGain();
    this.carveGain.gain.value = 0;
    carveSource.connect(this.carveFilter).connect(this.carveGain).connect(this.sfxBus);
    carveSource.start();
  }

  private windSourceSetup(ctx: AudioContext): void {
    const source = ctx.createBufferSource();
    source.buffer = this.noiseBuffer;
    source.loop = true;
    this.windFilter = ctx.createBiquadFilter();
    this.windFilter.type = 'lowpass';
    this.windFilter.frequency.value = 500;
    this.windGain = ctx.createGain();
    this.windGain.gain.value = 0;
    source.connect(this.windFilter).connect(this.windGain).connect(this.sfxBus as GainNode);
    source.start();
  }

  private createNoiseBuffer(ctx: AudioContext): AudioBuffer {
    const length = ctx.sampleRate * 2;
    const buffer = ctx.createBuffer(1, length, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < length; i++) data[i] = Math.random() * 2 - 1;
    return buffer;
  }

  private tone(
    type: OscillatorType,
    from: number,
    to: number,
    duration: number,
    peak: number,
    delay = 0,
  ): void {
    const ctx = this.context;
    if (!ctx || !this.sfxBus || !this.enabled) return;
    const start = ctx.currentTime + delay;
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.type = type;
    osc.frequency.setValueAtTime(from, start);
    osc.frequency.exponentialRampToValueAtTime(Math.max(to, 1), start + duration);
    gain.gain.setValueAtTime(0.0001, start);
    gain.gain.exponentialRampToValueAtTime(peak, start + 0.02);
    gain.gain.exponentialRampToValueAtTime(0.0001, start + duration);
    osc.connect(gain).connect(this.sfxBus);
    osc.start(start);
    osc.stop(start + duration + 0.05);
  }

  private noiseBurst(duration: number, peak: number, cutoff: number): void {
    const ctx = this.context;
    if (!ctx || !this.sfxBus || !this.noiseBuffer || !this.enabled) return;
    const start = ctx.currentTime;
    const source = ctx.createBufferSource();
    source.buffer = this.noiseBuffer;
    const filter = ctx.createBiquadFilter();
    filter.type = 'lowpass';
    filter.frequency.setValueAtTime(cutoff, start);
    filter.frequency.exponentialRampToValueAtTime(Math.max(cutoff * 0.3, 80), start + duration);
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(peak, start);
    gain.gain.exponentialRampToValueAtTime(0.0001, start + duration);
    source.connect(filter).connect(gain).connect(this.sfxBus);
    source.start(start);
    source.stop(start + duration + 0.05);
  }
}
